// 画像クイズの題材。[正解, 種類, Wikimedia Commons でさがす英語のことば]
// 画像は CC0（パブリックドメイン）のものだけを使う（picks.js で1枚ずつ選ぶ）

export const KINDS = {
  動物: { genre: '生き物・自然', prompt: 'この動物は？' },
  食べ物: { genre: '食べ物・飲み物', prompt: 'この食べ物は？' },
  乗り物: { genre: '乗り物・テクノロジー', prompt: 'この乗り物は？' },
  楽器: { genre: '芸術・伝統文化', prompt: 'この楽器は？' },
  道具: { genre: '暮らし', prompt: 'これは何？' },
  名所: { genre: '地理', prompt: 'この名所は？' },
  スポーツ: { genre: 'スポーツ', prompt: 'この道具を使うスポーツは？' },
};

export default [
  // 動物
  ['キリン', '動物', 'giraffe'],
  ['ゾウ', '動物', 'elephant'],
  ['ライオン', '動物', 'lion'],
  ['トラ', '動物', 'tiger'],
  ['パンダ', '動物', 'giant panda'],
  ['シマウマ', '動物', 'zebra'],
  ['ペンギン', '動物', 'penguin'],
  ['フラミンゴ', '動物', 'flamingo'],
  ['コアラ', '動物', 'koala'],
  ['カンガルー', '動物', 'kangaroo'],
  ['ラクダ', '動物', 'camel'],
  ['カバ', '動物', 'hippopotamus'],
  ['サイ', '動物', 'rhinoceros'],
  ['ゴリラ', '動物', 'gorilla'],
  ['ハリネズミ', '動物', 'hedgehog'],
  ['カメレオン', '動物', 'chameleon'],
  ['フクロウ', '動物', 'owl'],
  ['クジャク', '動物', 'peacock'],
  ['チーター', '動物', 'cheetah'],
  ['ワニ', '動物', 'crocodile'],
  ['カメ', '動物', 'tortoise'],
  ['タコ', '動物', 'octopus'],
  ['クラゲ', '動物', 'jellyfish'],
  ['ヒトデ', '動物', 'starfish'],
  ['テントウムシ', '動物', 'ladybird'],
  ['チョウ', '動物', 'butterfly'],
  ['ミツバチ', '動物', 'honey bee'],
  ['カエル', '動物', 'frog'],
  ['ウサギ', '動物', 'rabbit'],
  ['ヒツジ', '動物', 'sheep'],
  ['ウマ', '動物', 'horse'],
  ['ニワトリ', '動物', 'rooster'],
  ['ホッキョクグマ', '動物', 'polar bear'],
  ['アザラシ', '動物', 'seal animal'],
  ['イルカ', '動物', 'dolphin'],
  ['カピバラ', '動物', 'capybara'],
  ['ナマケモノ', '動物', 'sloth'],
  ['アルパカ', '動物', 'alpaca'],
  ['リス', '動物', 'squirrel'],
  ['オウム', '動物', 'parrot macaw'],
  // 食べ物
  ['パイナップル', '食べ物', 'pineapple'],
  ['イチゴ', '食べ物', 'strawberry'],
  ['スイカ', '食べ物', 'watermelon'],
  ['バナナ', '食べ物', 'banana'],
  ['ブロッコリー', '食べ物', 'broccoli'],
  ['トウモロコシ', '食べ物', 'corn cob'],
  ['キウイ', '食べ物', 'kiwifruit'],
  ['ドラゴンフルーツ', '食べ物', 'dragon fruit'],
  ['ザクロ', '食べ物', 'pomegranate'],
  ['レモン', '食べ物', 'lemon'],
  ['ピーマン', '食べ物', 'green bell pepper'],
  ['タマネギ', '食べ物', 'onion'],
  ['ブドウ', '食べ物', 'grapes'],
  ['カボチャ', '食べ物', 'pumpkin'],
  ['ナス', '食べ物', 'eggplant'],
  ['トマト', '食べ物', 'tomato'],
  ['ニンジン', '食べ物', 'carrot'],
  ['キャベツ', '食べ物', 'cabbage'],
  ['ピザ', '食べ物', 'pizza'],
  ['ハンバーガー', '食べ物', 'hamburger'],
  ['すし', '食べ物', 'sushi'],
  ['ドーナツ', '食べ物', 'doughnut'],
  ['クロワッサン', '食べ物', 'croissant'],
  ['ラーメン', '食べ物', 'ramen'],
  ['ギョーザ', '食べ物', 'gyoza'],
  ['おにぎり', '食べ物', 'onigiri'],
  ['パンケーキ', '食べ物', 'pancakes'],
  ['マカロン', '食べ物', 'macarons'],
  ['ポップコーン', '食べ物', 'popcorn'],
  ['クッキー', '食べ物', 'cookies'],
  // 乗り物
  ['自転車', '乗り物', 'bicycle'],
  ['新幹線', '乗り物', 'shinkansen'],
  ['飛行機', '乗り物', 'airliner'],
  ['ヘリコプター', '乗り物', 'helicopter'],
  ['熱気球', '乗り物', 'hot air balloon'],
  ['消防車', '乗り物', 'fire engine'],
  ['ヨット', '乗り物', 'sailboat'],
  ['ロケット', '乗り物', 'rocket launch'],
  ['バス', '乗り物', 'bus'],
  ['蒸気機関車', '乗り物', 'steam locomotive'],
  ['ショベルカー', '乗り物', 'excavator'],
  ['オートバイ', '乗り物', 'motorcycle'],
  // 楽器
  ['バイオリン', '楽器', 'violin'],
  ['ギター', '楽器', 'guitar'],
  ['トランペット', '楽器', 'trumpet'],
  ['ピアノ', '楽器', 'piano'],
  ['ハープ', '楽器', 'harp'],
  ['サクソフォーン', '楽器', 'saxophone'],
  ['アコーディオン', '楽器', 'accordion'],
  ['ドラム', '楽器', 'drum kit'],
  ['三味線', '楽器', 'shamisen'],
  ['箏', '楽器', 'koto instrument'],
  // 道具
  ['はさみ', '道具', 'scissors'],
  ['傘', '道具', 'umbrella'],
  ['めがね', '道具', 'eyeglasses'],
  ['鍵', '道具', 'key lock'],
  ['電球', '道具', 'light bulb'],
  ['地球儀', '道具', 'globe'],
  ['歯ブラシ', '道具', 'toothbrush'],
  ['鉛筆', '道具', 'pencils'],
  ['そろばん', '道具', 'abacus'],
  ['砂時計', '道具', 'hourglass'],
  ['方位磁針', '道具', 'compass'],
  ['顕微鏡', '道具', 'microscope'],
  // 名所
  ['東京タワー', '名所', 'Tokyo Tower'],
  ['エッフェル塔', '名所', 'Eiffel Tower'],
  ['ピラミッド', '名所', 'pyramids of Giza'],
  ['自由の女神像', '名所', 'Statue of Liberty'],
  ['姫路城', '名所', 'Himeji Castle'],
  ['凱旋門', '名所', 'Arc de Triomphe'],
  ['ビッグ・ベン', '名所', 'Big Ben'],
  ['ピサの斜塔', '名所', 'Leaning Tower of Pisa'],
  ['万里の長城', '名所', 'Great Wall of China'],
  ['タージ・マハル', '名所', 'Taj Mahal'],
  ['コロッセオ', '名所', 'Colosseum'],
  ['モアイ像', '名所', 'moai Easter Island'],
  ['富士山', '名所', 'Mount Fuji'],
  ['金閣寺', '名所', 'Kinkaku-ji'],
  ['東京スカイツリー', '名所', 'Tokyo Skytree'],
  ['ゴールデン・ゲート・ブリッジ', '名所', 'Golden Gate Bridge'],
  ['シドニー・オペラハウス', '名所', 'Sydney Opera House'],
  ['サグラダ・ファミリア', '名所', 'Sagrada Familia'],
  // スポーツ
  ['サッカー', 'スポーツ', 'soccer ball'],
  ['バスケットボール', 'スポーツ', 'basketball ball'],
  ['テニス', 'スポーツ', 'tennis racket'],
  ['野球', 'スポーツ', 'baseball glove'],
  ['バドミントン', 'スポーツ', 'shuttlecock'],
  ['ゴルフ', 'スポーツ', 'golf ball'],
  ['ボウリング', 'スポーツ', 'bowling pins'],
  ['ラグビー', 'スポーツ', 'rugby ball'],
];
